controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_logout:
    path: '/logout'
    controller: 'App\Controller\SecurityController::logout'
    methods: ['POST']
check_credential:
    path: /checkcredential
    controller: App\Controller\LoginController::checkCredential
    methods: [POST]
login:
    path: /login
    controller: App\Controller\LoginController::signIn
    methods: [POST]